<!DOCTYPE html>
<html>
<head>
	<title>Catalogo vestido</title>
	 <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">  
<?php 
$this->assets->outputCss(); 
$this->assets->outputJs();
?>
</head>
<body>
  <!--Titulo de la pagina -->
  <div class="header">
  <img src="public/img/logo.png">
    <h2>Catalogo de Vestidos</h2>
  </div>
  <br>
  <div id="reponse-container">
    
  </div>
  <br>

<!-- menu -->
<nav>
  <ul>
    <li>
      <a href="http://localhost/Boutique/">Inicio</a>
    </li>
    <?php 
if ($this->session->get('Login') == Null) {
 ?>
    <li>

      <a href="http://localhost/Boutique/Login" > iniciar Session </a>
    </li>
    <li>
      <a class="navbar-brand" href="http://localhost/Boutique/Registro" >Registro de usuariao </a>

    </li>
    <?php } ?>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Primavera otoño</a>
      <div class="dropdown-content">
        
        <a  href="http://localhost/Boutique/CatalogoVestido" style="color: black;" >Vestido</a>
        <a  href="http://localhost/Boutique/Catalogoblusa" style="color: black;" >Bulsas</a>
        
        <a  href="http://localhost/Boutique/CatalogoFalda" style="color: black;" >Faldas</a>
      </div>
    </li>
     <?php 

    if($this->session->has('Login'))
     
      {

     ?>
     <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">
          <label id="usuario">
            <?php echo  $this->session->get('Login');?>
            
          </label>
        </a>
        <div class="dropdown-content">
          <a class="dropdown-item" style="color: black;" <?php echo $this->tag->linkTo('Boutique/Index/Salir','Salir');?> </a>
        </div>
     </li>
     <button class="car" onclick="comprar();">
        <img class="carritoimg" src="public/img/iconos/compras.jpeg">
      </button>
      <?php } ?>
      

     
  </ul>
</nav>
<br>

<!--carrusel de la pagina-->

<div class="slideshow-container">
  <center>
  <div class="mySlides fade">
    <div class="numbertext">1/3</div>
    <img src="public/img/vestido/Vestido1.jpg">
    <div class="text">cation tex</div>
  </div>

    <div class="mySlides fade">
      <div class="numbertext">2/3</div>
      <img src="public/img/vestido/Vestido2.jpg">
      <div class="text">cation tex</div>
    </div>
    
    <div class="mySlides fade">
      <div class="numbertext">3/3</div>
      <img src="public/img/vestido/Vestido3.jpg">
      <div class="text">cation tex</div>
    </div>
  </center>
<a class="prev" onclick="plusSlides(-1)">&#10094</a>
<a class="next" onclick="plusSlides(1)">&#10095</a>

</div>

<!-- contenido de la pagina -->
<br>
<div class="row">
<?php 
foreach ($ves as $vest) {
?>

    <div class="column">
<a href="<?php echo $vest["id_PRO"] ?>">
<div id="marca<?php echo $vest['id_PRO'] ?>">
      
<h3 class="titulo">
  <?php echo $vest["Marca"] ?>
    
  </h3>

<center>
<img class="cat" src=<?php echo  $vest["Rutaimg"];?>>
</center>
<p class="Descripcion"><?php echo $vest["Descripcion"];?>
  <br>
  $<?php echo" ".$vest["Precio"]; ?>
</p>
</a>
</div>
<?php 

    if($this->session->has('Login'))
     
      {
?>
<button class="car"  onclick="myadd(<?php echo $vest['id_PRO'] ?>,<?php echo $vest["Precio"];?>);"><img src="public/img/iconos/carrito.png " height="30px" width="30px"></button>
</div>

<?php
 } else{
?>
<button class="car" onclick="com();"><img src="public/img/iconos/carrito.png " height="30px" width="30px"></button>
</div>
<?php
  }
}  
?>

</div>
<!--fooder de la pagina-->
<div class="container">
       <hr>
    <footer>

        <p class="tex">&copy; Company 2017 Boutique la Paz</p>
        <img class="graf" src="public/img/face.png"> Facebook Boutique la Paz
        <img class="graf" src="public/img/inst.png"> Instagram Boutique la Paz
        <img class="graf" src="public/img/tiwe.png"> Tiwetter Boutique la Paz
        
    </footer>
</div>

</body>
</html>

<script type="text/javascript">
  var slideindex=0;
  showSlides();
  function showSlides()
  {
      var i;
      var slides=document.getElementsByClassName("mySlides");
      
      for ( i = 0; i < slides.length; i++ ) {
        slides[i].style.display="none";
       }

       slideindex++;
       if (slideindex > slides.length) {slideindex=1}
        slides[slideindex-1].style.display="block";
      setTimeout(showSlides,2000);
  }
</script>