 <br>
  <!--Titulo de la pagina -->
  <br>
  <div class="header">
          <img src="public/img/logo.png">
  </div>
  <br>
<!--menu-->
<nav>
  <ul>
    
    <li>
      <a href="http://localhost/Boutique/">Inicio</a>
    </li>
    <?php 
if ($this->session->get('Login') == Null) {
 ?>
    <li>

      <a href="http://localhost/Boutique/Login" > iniciar Session </a>
    </li>
    <li>
      <a class="navbar-brand" href="http://localhost/Boutique/Registro" >Registro de usuariao </a>

    </li>
    <?php } ?>
    <li class="dropdown">
      <a href="javascript:void(0)" class="dropbtn">Primavera otoño</a>
      <div class="dropdown-content">
        
        <a  href="http://localhost/Boutique/CatalogoVestido" style="color: black;" >Vestido</a>
        <a  href="http://localhost/Boutique/Catalogoblusa" style="color: black;" >Bulsas</a>
        
        <a  href="http://localhost/Boutique/CatalogoFalda" style="color: black;" >Faldas</a>
      </div>
    </li>
     <?php 

    if($this->session->has('Login'))
     
      {

     ?>
     <li class="dropdown">
        <a href="javascript:void(0)" class="dropbtn">
          <?php echo  $this->session->get('Login');?>
        </a>
        <div class="dropdown-content">
          <a class="dropdown-item" style="color: black;" <?php echo $this->tag->linkTo('Boutique/Index/Salir','Salir');?> </a>
        </div>
     </li>
      <?php } ?>
      <li>
      <a id="myBtn" href="#">Acerca de</a>
      </li>
  </ul>

</nav>
 
  <div>
    Tiempo
  </div>
  <br>
  <!--cuerpo de la pagina-->
  
  <div class="row">
    <div class="column">
      <h3>Ofertas de Vestido</h3>
      
      <img src="public/img/Vestido.jpg" height="70%" width="80%" align="center">
      <p>
        Vestido de con estampados a solo por hoy 
        $120
      </p> 
    </div>
    <div class="column">
      <h3>ofertas de Jeans</h3>
      <img src="public/img/jaens.jpg" height="100%" width="80%" align="center">
      <p>
        Jeans en oferta a solo $200
      </p>
    </div>
    <div class="column">
      <h3>Ofertas de Blusas</h3> 
      <img src="public/img/blusa.jpg" height="70%" width="80%" align="center">
      <p>Blusa a solo $300</p>
    </div>
  </div>

<!--fooder de la pagina-->
<div class="container">
       <hr>
    <footer class="footer">

        <p class="tex">&copy; Company 2017 Boutique la Paz</p>
        <img class="graf" src="public/img/face.png"> Facebook Boutique la Paz
        <img class="graf" src="public/img/inst.png"> Instagram Boutique la Paz
        <img class="graf" src="public/img/tiwe.png"> Tiwetter Boutique la Paz
        
    </footer>
</div>


 <!--modal--->
  <div id="myModal" class="modal">
    
    <!--contenido del modal-->
    <div class="modal-content">
      <span class="close">&times;</span>
        <!--titulo de la pagina-->
        <div class="header">
        <img src="public/img/logo.png" height="50%" width="50%">
        </div>
        <br>
        <img style="float: left;" src="public/img/iconos/buap.png" height="60px" width="70px">
        <img style="float: right;" src="public/img/iconos/1.png" height="60px" width="70px">
        <h1>Benemérita universidad Autónoma de Puebla</h1>
        <h1>Facultad de ciencias de la Computación </h1>
        

        <p class="texmodal">Este proyecto es de la materia Aplicaciones web en la cual esta desarrollado en su totalidad con php y mysql. Algunos de los elementos fuero realizados con javascript por ejemplo la función del carito</p>

        <p class="texmodal">
          Los integrantes del desarrollo del proyecto son:
          <br>
          José Manuel Sánchez Juárez.
          <br>
          Mauricio Oropeza Benitez.
          <br>
          Ernesto Barrientos Tirso.
          <br>
          Gustavo Abraham Contreras Perez.
          <br>
          Victor Hugo Garcia Morales.

        </p>

    </div>
  </div>


<script type="text/javascript">
  // Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

</script>